# Include external config snippets
include=~/.config/foot/conf.d/colors.ini
[main]
term=foot
font=monospace:size=11
pad=8x8

[colors]
# Transparency (0.0 = invisible, 1.0 = solid, 0.85 = translucent)
alpha=0.85
background=000000
foreground=ffffff

[key-bindings]
show-urls-launch=Control+Shift+o
